repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.4
    hooks:
      - id: ruff-check
      - id: ruff-format


  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.0
    hooks:
      - id: mypy
        always_run: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json

  - repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: poetry run pylint src tests
      language: system
      types: [python]
      stages: [pre-push]
      always_run: true
    - id: pytest
      name: Run pytest
      entry: poetry run pytest
      language: system
      types: [python]
      stages: [pre-push]
      always_run: true

  # - repo: https://github.com/gtkacz/coverage-pre-commit
  #   rev: v0.1.1
  #   hooks:
  #   -   id: coverage-pre-commit
  #       args: [--provider=pytest, --fail-under=100, --extra-dependencies=pytest-xdist]
